// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mti.Persistence.Products;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mti.Persistence.Products.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20251020014417_initPrds")]
    partial class initPrds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CampaignProducts", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("CampaignId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CampaignProducts", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("PolicyTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyTypeId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Campaigns_PolicyTypeId_Code");

                    b.ToTable("Campaigns", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoverageAvailabilityTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoverageLevelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoverageTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("CoverageAvailabilityTypeId");

                    b.HasIndex("CoverageLevelId");

                    b.HasIndex("CoverageTypeId");

                    b.HasIndex("ProductId", "CoverageAvailabilityTypeId", "CoverageTypeId", "CoverageLevelId")
                        .IsUnique()
                        .HasDatabaseName("IX_CoverageAvailabilities_ProductCoverages");

                    b.ToTable("CoverageAvailabilities", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageAvailabilityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_CoverageAvailabilityTypes_Code");

                    b.ToTable("CoverageAvailabilityTypes", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageBasis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_CoverageBasises_Code");

                    b.ToTable("CoverageBasises", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoverageBasisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoverageLevelTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoverageBasisId");

                    b.HasIndex("CoverageLevelTypeId");

                    b.HasIndex("UnitId");

                    b.ToTable("CoverageLevels", "products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageLevelType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_CoverageLevelTypes_Code");

                    b.ToTable("CoverageLevelTypes", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_CoverageTypes_Code");

                    b.ToTable("CoverageTypes", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageTypeComposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromCoverageTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid>("ToCoverageTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ToCoverageTypeId");

                    b.HasIndex("FromCoverageTypeId", "ToCoverageTypeId")
                        .IsUnique()
                        .HasDatabaseName("IX_CoverageTypeCompositions_FromToCoverageTypeId");

                    b.ToTable("CoverageTypeCompositions", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.InsuranceRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoverageLevelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoverageTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PeriodTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductFeatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RateAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoverageLevelId");

                    b.HasIndex("CoverageTypeId");

                    b.HasIndex("PeriodTypeId");

                    b.HasIndex("ProductFeatureId");

                    b.HasIndex("UnitId");

                    b.HasIndex("ProductId", "CoverageTypeId", "CoverageLevelId", "ProductFeatureId", "UnitId", "PeriodTypeId", "EffectiveDate")
                        .IsUnique()
                        .HasDatabaseName("IX_InsuranceRates_ProductFeatures_Coverages");

                    b.ToTable("InsuranceRates", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.PeriodType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_PeriodTypes_Code");

                    b.ToTable("PeriodTypes", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.PolicyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_PolicyTypes_Code");

                    b.ToTable("PolicyTypes", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateOnly>("SaleEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("SaleStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_Code");

                    b.ToTable("Products", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.ProductFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductFeatureTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeatureTypeId");

                    b.ToTable("ProductFeatures", "products");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.ProductFeatureAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductFeatureAvailabilityTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductFeatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ProductFeatureAvailabilityTypeId");

                    b.HasIndex("ProductFeatureId");

                    b.HasIndex("ProductId", "ProductFeatureAvailabilityTypeId", "ProductFeatureId")
                        .HasDatabaseName("IX_ProductFeatureAvailabilities_ProductFeatures");

                    b.ToTable("ProductFeatureAvailabilities", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.ProductFeatureAvailabilityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductFeatureAvailabilityTypes_Code");

                    b.ToTable("ProductFeatureAvailabilityTypes", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.ProductFeatureType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductFeatureTypes_Code");

                    b.ToTable("ProductFeatureTypes", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid>("UnitCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UnitCategoryId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Units_UnitCategoryId_Code");

                    b.ToTable("Units", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.UnitCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("UnitCategories", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleFuelType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_VehicleFuelTypes_Code");

                    b.ToTable("VehicleFuelTypes", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Max")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Min")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleTypeVoluntaryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("VehicleTypeVoluntaryId");

                    b.ToTable("VehicleSizes", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleTypeCompulsory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid>("VehicleTypeVoluntaryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeVoluntaryId", "Code")
                        .IsUnique()
                        .HasDatabaseName("IX_VehicleTypeCompulsories_VehicleTypeVoluntaryId_Code");

                    b.ToTable("VehicleTypeCompulsories", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleTypeVoluntary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid>("VehicleFuelTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleUsageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_VehicleTypeVoluntaries_Code");

                    b.HasIndex("VehicleTypeId");

                    b.HasIndex("VehicleUsageId");

                    b.HasIndex("VehicleFuelTypeId", "VehicleTypeId", "VehicleUsageId")
                        .IsUnique()
                        .HasDatabaseName("IX_VehicleTypeVoluntaries_VehicleFuelTypeUsages");

                    b.ToTable("VehicleTypeVoluntaries", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("VehicleUsages", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleWorkshopType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LookupNames")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<decimal>("Revision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_VehicleWorkshopTypes_Code");

                    b.HasIndex("LookupNames")
                        .HasDatabaseName("IX_VehicleWorkshopTypes_LookupNames");

                    b.ToTable("VehicleWorkshopTypes", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageAmount", b =>
                {
                    b.HasBaseType("Mti.Domain.Products.Entities.CoverageLevel");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.ToTable("CoverageAmounts", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageLimit", b =>
                {
                    b.HasBaseType("Mti.Domain.Products.Entities.CoverageLevel");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.ToTable("CoverageLimits", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageRange", b =>
                {
                    b.HasBaseType("Mti.Domain.Products.Entities.CoverageLevel");

                    b.Property<decimal>("MaximumAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinimumAmount")
                        .HasColumnType("numeric");

                    b.ToTable("CoverageRanges", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleCompulsoryFeature", b =>
                {
                    b.HasBaseType("Mti.Domain.Products.Entities.ProductFeature");

                    b.Property<decimal>("Max")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Min")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VehicleTypeCompulsoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VehicleTypeVoluntaryId")
                        .HasColumnType("uuid");

                    b.HasIndex("UnitId");

                    b.HasIndex("VehicleTypeCompulsoryId");

                    b.HasIndex("VehicleTypeVoluntaryId", "Min", "UnitId", "VehicleTypeCompulsoryId")
                        .IsUnique()
                        .HasDatabaseName("IX_VehicleCompulsoryFeatures_VehicleTypeVoluntaryId_Min_UnitId_VehicleTypeCompulsoryId");

                    b.ToTable("VehicleCompulsoryFeatures", "products");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleVoluntaryFeature", b =>
                {
                    b.HasBaseType("Mti.Domain.Products.Entities.ProductFeature");

                    b.Property<Guid?>("VehicleTypeVoluntaryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VehicleWorkshopTypeId")
                        .HasColumnType("uuid");

                    b.HasIndex("VehicleTypeVoluntaryId");

                    b.HasIndex("VehicleWorkshopTypeId", "VehicleTypeVoluntaryId")
                        .IsUnique()
                        .HasDatabaseName("IX_VehicleVoluntaryFeatures_VehicleWorkshopTypeId_VehicleTypeVoluntaryId");

                    b.ToTable("VehicleVoluntaryFeatures", "products");
                });

            modelBuilder.Entity("CampaignProducts", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.Domain.Products.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.Campaign", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.PolicyType", "PolicyType")
                        .WithMany()
                        .HasForeignKey("PolicyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("CampaignId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("CampaignId");

                            b1.ToTable("Campaigns", "products");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("PolicyType");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageAvailability", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.CoverageAvailabilityType", "CoverageAvailabilityType")
                        .WithMany()
                        .HasForeignKey("CoverageAvailabilityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.Domain.Products.Entities.CoverageLevel", "CoverageLevel")
                        .WithMany()
                        .HasForeignKey("CoverageLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.Domain.Products.Entities.CoverageType", "CoverageType")
                        .WithMany()
                        .HasForeignKey("CoverageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.Domain.Products.Entities.Product", "Product")
                        .WithMany("CoverageAvailabilities")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoverageAvailabilityType");

                    b.Navigation("CoverageLevel");

                    b.Navigation("CoverageType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageAvailabilityType", b =>
                {
                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("CoverageAvailabilityTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("CoverageAvailabilityTypeId");

                            b1.ToTable("CoverageAvailabilityTypes", "products");

                            b1.WithOwner()
                                .HasForeignKey("CoverageAvailabilityTypeId");
                        });

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageBasis", b =>
                {
                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("CoverageBasisId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("CoverageBasisId");

                            b1.ToTable("CoverageBasises", "products");

                            b1.WithOwner()
                                .HasForeignKey("CoverageBasisId");
                        });

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageLevel", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.CoverageBasis", "CoverageBasis")
                        .WithMany()
                        .HasForeignKey("CoverageBasisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.Domain.Products.Entities.CoverageLevelType", "CoverageLevelType")
                        .WithMany()
                        .HasForeignKey("CoverageLevelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.Domain.Products.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoverageBasis");

                    b.Navigation("CoverageLevelType");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageLevelType", b =>
                {
                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("CoverageLevelTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("CoverageLevelTypeId");

                            b1.ToTable("CoverageLevelTypes", "products");

                            b1.WithOwner()
                                .HasForeignKey("CoverageLevelTypeId");
                        });

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageType", b =>
                {
                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("CoverageTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("CoverageTypeId");

                            b1.ToTable("CoverageTypes", "products");

                            b1.WithOwner()
                                .HasForeignKey("CoverageTypeId");
                        });

                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("CoverageTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("Name");

                            b1.HasKey("CoverageTypeId");

                            b1.ToTable("CoverageTypes", "products");

                            b1.WithOwner()
                                .HasForeignKey("CoverageTypeId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageTypeComposition", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.CoverageType", "FromCoverageType")
                        .WithMany("ToCompositions")
                        .HasForeignKey("FromCoverageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.Domain.Products.Entities.CoverageType", "ToCoverageType")
                        .WithMany("FromCompositions")
                        .HasForeignKey("ToCoverageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromCoverageType");

                    b.Navigation("ToCoverageType");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.InsuranceRate", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.CoverageLevel", "CoverageLevel")
                        .WithMany()
                        .HasForeignKey("CoverageLevelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mti.Domain.Products.Entities.CoverageType", "CoverageType")
                        .WithMany()
                        .HasForeignKey("CoverageTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mti.Domain.Products.Entities.PeriodType", "PeriodType")
                        .WithMany()
                        .HasForeignKey("PeriodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.Domain.Products.Entities.ProductFeature", "ProductFeature")
                        .WithMany()
                        .HasForeignKey("ProductFeatureId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mti.Domain.Products.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.Domain.Products.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoverageLevel");

                    b.Navigation("CoverageType");

                    b.Navigation("PeriodType");

                    b.Navigation("Product");

                    b.Navigation("ProductFeature");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.PolicyType", b =>
                {
                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("PolicyTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("Name");

                            b1.HasKey("PolicyTypeId");

                            b1.ToTable("PolicyTypes", "products");

                            b1.WithOwner()
                                .HasForeignKey("PolicyTypeId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.Product", b =>
                {
                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products", "products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.ProductFeature", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.ProductFeatureType", "ProductFeatureType")
                        .WithMany()
                        .HasForeignKey("ProductFeatureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductFeatureType");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.ProductFeatureAvailability", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.ProductFeatureAvailabilityType", "ProductFeatureAvailabilityType")
                        .WithMany()
                        .HasForeignKey("ProductFeatureAvailabilityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.Domain.Products.Entities.ProductFeature", "ProductFeature")
                        .WithMany()
                        .HasForeignKey("ProductFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.Domain.Products.Entities.Product", "Product")
                        .WithMany("ProductFeatureAvailabilities")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductFeature");

                    b.Navigation("ProductFeatureAvailabilityType");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.ProductFeatureAvailabilityType", b =>
                {
                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("ProductFeatureAvailabilityTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("ProductFeatureAvailabilityTypeId");

                            b1.ToTable("ProductFeatureAvailabilityTypes", "products");

                            b1.WithOwner()
                                .HasForeignKey("ProductFeatureAvailabilityTypeId");
                        });

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.ProductFeatureType", b =>
                {
                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("ProductFeatureTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("ProductFeatureTypeId");

                            b1.ToTable("ProductFeatureTypes", "products");

                            b1.WithOwner()
                                .HasForeignKey("ProductFeatureTypeId");
                        });

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.Unit", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.UnitCategory", "UnitCategory")
                        .WithMany()
                        .HasForeignKey("UnitCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("UnitId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("Name");

                            b1.HasKey("UnitId");

                            b1.ToTable("Units", "products");

                            b1.WithOwner()
                                .HasForeignKey("UnitId");
                        });

                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Symbol", "Symbol", b1 =>
                        {
                            b1.Property<Guid>("UnitId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("Symbol");

                            b1.HasKey("UnitId");

                            b1.ToTable("Units", "products");

                            b1.WithOwner()
                                .HasForeignKey("UnitId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Symbol");

                    b.Navigation("UnitCategory");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.UnitCategory", b =>
                {
                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Code", "Code", b1 =>
                        {
                            b1.Property<Guid>("UnitCategoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Code");

                            b1.HasKey("UnitCategoryId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_UnitCategories_Code");

                            b1.ToTable("UnitCategories", "products");

                            b1.WithOwner()
                                .HasForeignKey("UnitCategoryId");
                        });

                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("UnitCategoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Name");

                            b1.HasKey("UnitCategoryId");

                            b1.ToTable("UnitCategories", "products");

                            b1.WithOwner()
                                .HasForeignKey("UnitCategoryId");
                        });

                    b.Navigation("Code")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleFuelType", b =>
                {
                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("VehicleFuelTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("Name");

                            b1.HasKey("VehicleFuelTypeId");

                            b1.ToTable("VehicleFuelTypes", "products");

                            b1.WithOwner()
                                .HasForeignKey("VehicleFuelTypeId");
                        });

                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Prefix", "Prefix", b1 =>
                        {
                            b1.Property<Guid>("VehicleFuelTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("Prefix");

                            b1.HasKey("VehicleFuelTypeId");

                            b1.ToTable("VehicleFuelTypes", "products");

                            b1.WithOwner()
                                .HasForeignKey("VehicleFuelTypeId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Prefix")
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleSize", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.Domain.Products.Entities.VehicleTypeVoluntary", "VehicleTypeVoluntary")
                        .WithMany("VehicleSizes")
                        .HasForeignKey("VehicleTypeVoluntaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");

                    b.Navigation("VehicleTypeVoluntary");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleType", b =>
                {
                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Code", "Code", b1 =>
                        {
                            b1.Property<Guid>("VehicleTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Code");

                            b1.HasKey("VehicleTypeId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_VehicleTypes_Code");

                            b1.ToTable("VehicleTypes", "products");

                            b1.WithOwner()
                                .HasForeignKey("VehicleTypeId");
                        });

                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("VehicleTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("Name");

                            b1.HasKey("VehicleTypeId");

                            b1.ToTable("VehicleTypes", "products");

                            b1.WithOwner()
                                .HasForeignKey("VehicleTypeId");
                        });

                    b.Navigation("Code")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleTypeCompulsory", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.VehicleTypeVoluntary", "VehicleTypeVoluntary")
                        .WithMany("VehicleTypeCompulsories")
                        .HasForeignKey("VehicleTypeVoluntaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("VehicleTypeCompulsoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("VehicleTypeCompulsoryId");

                            b1.ToTable("VehicleTypeCompulsories", "products");

                            b1.WithOwner()
                                .HasForeignKey("VehicleTypeCompulsoryId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("VehicleTypeVoluntary");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleTypeVoluntary", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.VehicleFuelType", "VehicleFuelType")
                        .WithMany()
                        .HasForeignKey("VehicleFuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.Domain.Products.Entities.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.Domain.Products.Entities.VehicleUsage", "VehicleUsage")
                        .WithMany()
                        .HasForeignKey("VehicleUsageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("VehicleTypeVoluntaryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("VehicleTypeVoluntaryId");

                            b1.ToTable("VehicleTypeVoluntaries", "products");

                            b1.WithOwner()
                                .HasForeignKey("VehicleTypeVoluntaryId");
                        });

                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("VehicleTypeVoluntaryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("Name");

                            b1.HasKey("VehicleTypeVoluntaryId");

                            b1.ToTable("VehicleTypeVoluntaries", "products");

                            b1.WithOwner()
                                .HasForeignKey("VehicleTypeVoluntaryId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("VehicleFuelType");

                    b.Navigation("VehicleType");

                    b.Navigation("VehicleUsage");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleUsage", b =>
                {
                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Code", "Code", b1 =>
                        {
                            b1.Property<Guid>("VehicleUsageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Code");

                            b1.HasKey("VehicleUsageId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_VehicleUsages_Code");

                            b1.ToTable("VehicleUsages", "products");

                            b1.WithOwner()
                                .HasForeignKey("VehicleUsageId");
                        });

                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("VehicleUsageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("Name");

                            b1.HasKey("VehicleUsageId");

                            b1.ToTable("VehicleUsages", "products");

                            b1.WithOwner()
                                .HasForeignKey("VehicleUsageId");
                        });

                    b.Navigation("Code")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleWorkshopType", b =>
                {
                    b.OwnsOne("Mti.Domain.Products.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("VehicleWorkshopTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("Name");

                            b1.HasKey("VehicleWorkshopTypeId");

                            b1.ToTable("VehicleWorkshopTypes", "products");

                            b1.WithOwner()
                                .HasForeignKey("VehicleWorkshopTypeId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageAmount", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.CoverageLevel", null)
                        .WithOne()
                        .HasForeignKey("Mti.Domain.Products.Entities.CoverageAmount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageLimit", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.CoverageLevel", null)
                        .WithOne()
                        .HasForeignKey("Mti.Domain.Products.Entities.CoverageLimit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageRange", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.CoverageLevel", null)
                        .WithOne()
                        .HasForeignKey("Mti.Domain.Products.Entities.CoverageRange", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleCompulsoryFeature", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.ProductFeature", null)
                        .WithOne()
                        .HasForeignKey("Mti.Domain.Products.Entities.VehicleCompulsoryFeature", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.Domain.Products.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.HasOne("Mti.Domain.Products.Entities.VehicleTypeCompulsory", "VehicleTypeCompulsory")
                        .WithMany()
                        .HasForeignKey("VehicleTypeCompulsoryId");

                    b.HasOne("Mti.Domain.Products.Entities.VehicleTypeVoluntary", "VehicleTypeVoluntary")
                        .WithMany()
                        .HasForeignKey("VehicleTypeVoluntaryId");

                    b.Navigation("Unit");

                    b.Navigation("VehicleTypeCompulsory");

                    b.Navigation("VehicleTypeVoluntary");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleVoluntaryFeature", b =>
                {
                    b.HasOne("Mti.Domain.Products.Entities.ProductFeature", null)
                        .WithOne()
                        .HasForeignKey("Mti.Domain.Products.Entities.VehicleVoluntaryFeature", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mti.Domain.Products.Entities.VehicleTypeVoluntary", "VehicleTypeVoluntary")
                        .WithMany()
                        .HasForeignKey("VehicleTypeVoluntaryId");

                    b.HasOne("Mti.Domain.Products.Entities.VehicleWorkshopType", "VehicleWorkshopType")
                        .WithMany()
                        .HasForeignKey("VehicleWorkshopTypeId");

                    b.Navigation("VehicleTypeVoluntary");

                    b.Navigation("VehicleWorkshopType");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.CoverageType", b =>
                {
                    b.Navigation("FromCompositions");

                    b.Navigation("ToCompositions");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.Product", b =>
                {
                    b.Navigation("CoverageAvailabilities");

                    b.Navigation("ProductFeatureAvailabilities");
                });

            modelBuilder.Entity("Mti.Domain.Products.Entities.VehicleTypeVoluntary", b =>
                {
                    b.Navigation("VehicleSizes");

                    b.Navigation("VehicleTypeCompulsories");
                });
#pragma warning restore 612, 618
        }
    }
}
